// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlfqbcaoiuoluqjnojjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZnFiY2FvaXVvbHVxam5vampuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDk3MDgsImV4cCI6MjA2MjQ4NTcwOH0.xEMkRqLkbJ4H6EDDldGfjSmXSrkd8FeNxlOq3rwfixY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);